# Generated by Django 4.2.13 on 2024-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['screen_number'], 'verbose_name': 'Screen', 'verbose_name_plural': 'Screens'},
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('date', 'show_time', 'screen'), name='unique_show'),
        ),
    ]
