# Generated by Django 4.2.13 on 2024-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movie_long_description_movie_sort_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sort_Description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
