# Generated by Django 4.2.13 on 2024-11-17 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_movie_sort_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('profilePhoto', models.ImageField(upload_to='castImages')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='home.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
