# Generated by Django 4.2.13 on 2024-11-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_moviecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviecast',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
