# Generated by Django 4.2.13 on 2024-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_movie_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sort_Description',
            field=models.TextField(default='Movies have always been a something good and better random text', max_length=50),
        ),
    ]
