# Generated by Django 5.1.2 on 2024-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_movie_sort_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
