# Generated by Django 4.2.13 on 2024-10-26 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('catagory', models.CharField(choices=[('GUJARATI', 'Gujarati'), ('SOUTH INDIAN', 'South Indian'), ('KASHMIRI', 'Kashmiri'), ('MALVANI', 'Malvani')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateField()),
                ('payment_status', models.CharField(choices=[(0, 'pending'), (2, 'complete'), (3, 'failed')], max_length=20)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodOrders', to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('item_Price', models.IntegerField()),
                ('foo_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='food.fooditem')),
                ('food_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='food.foodorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
